server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: materials-management-service

  # Configuración de base de datos PostgreSQL
  datasource:
    url: ${DB_URL:jdbc:postgresql://gondola.proxy.rlwy.net:47582/railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:MhjFVUvDAZjxxNNCbFBuHMqEwlftgzdu}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # Configuración JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: America/Bogota

  # Configuración de perfiles
  profiles:
    active: development

# Configuración del servicio de autenticación
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

# Configuración de logging
logging:
  level:
    com.materials.management: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/materials-management.log

# Configuración de documentación OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Configuración específica de la aplicación
app:
  name: "Sistema de Gestión de Materiales"
  version: "1.0.0"
  description: "API RESTful para la administración de materiales"