---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.materials.management: INFO
    org.springframework.security: WARN